In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('DateFruit_Dataset.csv')

In [ ]:
df.head() #34 features and 1 target variable

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [ ]:
df.isnull().sum() #preprocessed data, no null values

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [5]:
df.shape

(898, 35)

In [6]:
df.info() #all features are numerical, target variable is categorical

<class 'pandas.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           898 non-null    int64
 1   PERIMETER      898 non-null    float64
 2   MAJOR_AXIS     898 non-null    float64
 3   MINOR_AXIS     898 non-null    float64
 4   ECCENTRICITY   898 non-null    float64
 5   EQDIASQ        898 non-null    float64
 6   SOLIDITY       898 non-null    float64
 7   CONVEX_AREA    898 non-null    int64
 8   EXTENT         898 non-null    float64
 9   ASPECT_RATIO   898 non-null    float64
 10  ROUNDNESS      898 non-null    float64
 11  COMPACTNESS    898 non-null    float64
 12  SHAPEFACTOR_1  898 non-null    float64
 13  SHAPEFACTOR_2  898 non-null    float64
 14  SHAPEFACTOR_3  898 non-null    float64
 15  SHAPEFACTOR_4  898 non-null    float64
 16  MeanRR         898 non-null    float64
 17  MeanRG         898 non-null    float64
 18  MeanRB         898 non-null    float64
 19  StdDevRR       898 non-null    float64
 20  StdDevRG       898 non-null    float64
 21  StdDevRB       898 non-null    float64
 22  SkewRR         898 non-null    float64
 23  SkewRG         898 non-null    float64
 24  SkewRB         898 non-null    float64
 25  KurtosisRR     898 non-null    float64
 26  KurtosisRG     898 non-null    float64
 27  KurtosisRB     898 non-null    float64
 28  EntropyRR      898 non-null    int64
 29  EntropyRG      898 non-null    int64
 30  EntropyRB      898 non-null    int64
 31  ALLdaub4RR     898 non-null    float64
 32  ALLdaub4RG     898 non-null    float64
 33  ALLdaub4RB     898 non-null    float64
 34  Class          898 non-null    str
dtypes: float64(29), int64(5), str(1)
memory usage: 245.7 KB

In [8]:
df.describe() #no outliers, all features are normally distributed

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
count,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,898.000000,...,898.000000,898.000000,898.000000,898.000000,8.980000e+02,8.980000e+02,8.980000e+02,898.000000,898.000000,898.000000
mean,298295.207127,2057.660953,750.811994,495.872785,0.737468,604.577938,0.981840,303845.592428,0.736267,2.131102,...,0.250518,4.247845,5.110894,3.780928,-3.185021e+10,-2.901860e+10,-2.771876e+10,50.082888,48.805681,48.098393
std,107245.205337,410.012459,144.059326,114.268917,0.088727,119.593888,0.018157,108815.656947,0.053745,17.820778,...,0.632918,2.892357,3.745463,2.049831,2.037241e+10,1.712952e+10,1.484137e+10,16.063125,14.125911,10.813862
min,1987.000000,911.828000,336.722700,2.283200,0.344800,50.298400,0.836600,2257.000000,0.512300,1.065300,...,-1.029100,1.708200,1.607600,1.767200,-1.091224e+11,-9.261697e+10,-8.747177e+10,15.191100,20.524700,22.130000
25%,206948.000000,1726.091500,641.068650,404.684375,0.685625,513.317075,0.978825,210022.750000,0.705875,1.373725,...,-0.196950,2.536625,2.508850,2.577275,-4.429444e+10,-3.894638e+10,-3.564534e+10,38.224425,38.654525,39.250725
50%,319833.000000,2196.345450,791.363400,495.054850,0.754700,638.140950,0.987300,327207.000000,0.746950,1.524150,...,0.135550,3.069800,3.127800,3.080700,-2.826156e+10,-2.620990e+10,-2.392928e+10,53.841300,50.337800,49.614100
75%,382573.000000,2389.716575,858.633750,589.031700,0.802150,697.930525,0.991800,388804.000000,0.775850,1.674750,...,0.593950,4.449850,7.320400,4.283125,-1.460482e+10,-1.433105e+10,-1.660367e+10,63.063350,59.573600,56.666675
max,546063.000000,2811.997100,1222.723000,766.453600,1.000000,833.827900,0.997400,552598.000000,0.856200,535.525700,...,3.092300,26.171100,26.736700,32.249500,-1.627316e+08,-5.627727e+08,-4.370435e+08,79.828900,83.064900,74.104600

In [9]:
X = df.drop('Class', axis=1)
y = df['Class']

In [10]:
X.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,0.6019,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,0.4134,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,0.9183,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,1.8028,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,0.8865,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666

In [11]:
df["Class"].unique()

<StringArray>
['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY']
Length: 7, dtype: str

In [15]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
X_train

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
880,364338,2385.5110,849.6287,548.4377,0.7638,681.0944,0.9874,368969,0.7596,1.5492,...,0.3835,2.5413,2.7010,4.7956,-45702238208,-31309285376,-31791349760,54.5422,46.1706,47.5687
740,343379,2360.4670,919.1130,479.2314,0.8533,661.2138,0.9657,355591,0.6926,1.9179,...,0.8084,13.2536,10.8915,5.0327,-6173152768,-10177111040,-13946608640,20.5354,27.7553,33.2095
231,80044,1059.0460,378.1419,270.6614,0.6983,319.2416,0.9883,80990,0.7521,1.3971,...,-0.1599,2.2247,2.4509,2.2165,-9834114048,-9082079232,-8377428480,54.3915,53.0591,50.5000
388,394009,2279.7581,770.8477,654.0494,0.5292,708.2852,0.9945,396190,0.7632,1.1786,...,1.6654,5.7796,9.1424,7.8056,-18411845632,-23242752000,-23591233536,34.5177,38.9835,38.4695
118,242874,1843.9160,647.9982,479.8817,0.6720,556.0906,0.9906,245181,0.7818,1.3503,...,-0.3694,2.4534,2.2759,2.5079,-46650236928,-40748339200,-32199612416,66.5225,62.6833,56.9092
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,169573,1548.9830,594.8965,364.4516,0.7904,464.6580,0.9932,170738,0.8245,1.6323,...,-0.6257,2.4879,2.1186,2.4125,-35847098368,-33293408256,-27052677120,69.5829,67.4267,61.7498
270,102142,1223.5020,441.7251,296.5040,0.7412,360.6262,0.9863,103559,0.7847,1.4898,...,-0.5385,3.7325,3.9749,3.0696,-20307597312,-20240594944,-18247018496,68.7153,69.4312,65.9034
860,212397,1773.1410,649.3710,418.6798,0.7644,520.0310,0.9773,217331,0.7605,1.5510,...,0.1680,2.8597,2.8887,3.0498,-21660262400,-16450807808,-15513940992,50.1400,43.9826,43.0455
435,441826,2486.4771,942.0581,603.1290,0.7682,750.0336,0.9948,444138,0.8075,1.5620,...,1.7484,7.9695,9.3755,7.3022,-36332118016,-32863416320,-37779701760,43.0456,41.0627,43.2121
102,212744,1720.3030,628.2148,432.3847,0.7254,520.4556,0.9918,214501,0.7818,1.4529,...,-0.2504,1.9579,2.1380,2.4907,-28291532800,-27781709824,-24325011456,55.4153,54.8434,52.6176

In [20]:
X_test

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,SkewRB,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB
331,143957,1452.2620,523.1368,352.3305,0.7392,428.1259,0.9844,146236,0.7746,1.4848,...,-0.3565,4.1478,3.4278,2.4134,-36987568128,-34249711616,-23752157184,77.3446,75.2287,62.9057
638,260563,1975.3740,762.5055,437.8510,0.8187,575.9854,0.9871,263977,0.6648,1.7415,...,0.3581,7.7778,16.2644,3.6606,-2424508160,-4791147520,-8197618688,16.2304,22.3860,28.8860
326,154245,1503.5980,546.4366,361.8018,0.7494,443.1601,0.9883,156070,0.7420,1.5103,...,0.3657,2.4202,2.9624,3.0045,-14960579584,-14010061824,-14057613312,48.2049,46.8561,46.4054
848,317794,2280.9690,875.5868,525.3380,0.8000,636.1037,0.9016,352462,0.6484,1.6667,...,0.3719,2.2682,2.1522,2.9676,-47417053184,-39451316224,-33127270400,58.7696,54.0476,50.8977
39,402279,2295.8630,798.9365,643.2753,0.5931,715.6797,0.9936,404887,0.7867,1.2420,...,1.9477,5.5889,12.5304,9.9496,-30746945536,-32178810880,-35126345728,43.7705,45.6162,46.3010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
777,283770,2096.7639,775.8751,468.8516,0.7968,601.0883,0.9737,291436,0.6751,1.6548,...,0.8440,11.0456,12.1213,6.1299,-4560918528,-7281993216,-9060293632,20.5245,25.8721,29.4805
25,381508,2239.7891,734.2203,666.2502,0.4202,696.9584,0.9919,384642,0.7398,1.1020,...,2.0740,6.6729,10.5392,9.3474,-25635362816,-25228310528,-28113027072,41.0071,41.1774,41.5364
84,253276,1961.0400,740.2677,437.3487,0.8068,567.8741,0.9822,257864,0.7493,1.6926,...,-0.1425,2.0920,1.9879,2.1549,-45574098944,-41109114880,-35898662912,64.4454,61.4443,58.3921
10,364495,2216.4900,790.9014,590.7698,0.6649,681.2411,0.9949,366374,0.7658,1.3388,...,0.9283,3.0514,4.3653,6.0898,-41679380480,-40727969792,-37574615040,52.7269,52.9888,50.3108
332,156030,1566.9790,595.6793,384.2388,0.7641,445.7169,0.9118,171132,0.6319,1.5503,...,-0.3529,2.5952,2.3904,2.6668,-33837977600,-33563627520,-25646532608,70.7212,71.3609,63.4659

In [21]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

## ANN

In [22]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [23]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [24]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [26]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

In [27]:
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [28]:
#Build Our ANN Model
class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 7)
        )

    def forward(self, x):
        return self.model(x)

In [29]:
model = ANN()

#loss function and optimizer
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [30]:
# Training the nn
epochs = 100
for epoch in range(epochs):
    model.train()

    running_loss = 0.0
    for xb, yb in train_loader:
        optimizer.zero_grad() # zero the gradients

        outputs = model(xb) # forward pass
        loss = criteria(outputs, yb) # compute loss
        loss.backward() # backward pass
        optimizer.step() # update weights

        running_loss += loss.item()
    
    train_loss = running_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{epochs}, Loss: {train_loss:.4f}")

Epoch 1/100, Loss: 1.6471
Epoch 2/100, Loss: 1.1524
Epoch 3/100, Loss: 0.7868
Epoch 4/100, Loss: 0.5836
Epoch 5/100, Loss: 0.4774
Epoch 6/100, Loss: 0.4035
Epoch 7/100, Loss: 0.3442
Epoch 8/100, Loss: 0.3102
Epoch 9/100, Loss: 0.2761
Epoch 10/100, Loss: 0.2600
Epoch 11/100, Loss: 0.2342
Epoch 12/100, Loss: 0.2229
Epoch 13/100, Loss: 0.2095
Epoch 14/100, Loss: 0.1944
Epoch 15/100, Loss: 0.1939
Epoch 16/100, Loss: 0.1757
Epoch 17/100, Loss: 0.1751
Epoch 18/100, Loss: 0.1637
Epoch 19/100, Loss: 0.1611
Epoch 20/100, Loss: 0.1512
Epoch 21/100, Loss: 0.1410
Epoch 22/100, Loss: 0.1426
Epoch 23/100, Loss: 0.1403
Epoch 24/100, Loss: 0.1295
Epoch 25/100, Loss: 0.1295
Epoch 26/100, Loss: 0.1302
Epoch 27/100, Loss: 0.1238
Epoch 28/100, Loss: 0.1198
Epoch 29/100, Loss: 0.1125
Epoch 30/100, Loss: 0.1166
Epoch 31/100, Loss: 0.1115
Epoch 32/100, Loss: 0.1061
Epoch 33/100, Loss: 0.1104
Epoch 34/100, Loss: 0.1068
Epoch 35/100, Loss: 0.1155
Epoch 36/100, Loss: 0.1016
Epoch 37/100, Loss: 0.0952
Epoch 38/100, Loss: 0.0945
Epoch 39/100, Loss: 0.0964
Epoch 40/100, Loss: 0.0876
Epoch 41/100, Loss: 0.0850
Epoch 42/100, Loss: 0.0838
Epoch 43/100, Loss: 0.0850
Epoch 44/100, Loss: 0.0820
Epoch 45/100, Loss: 0.0797
Epoch 46/100, Loss: 0.0772
Epoch 47/100, Loss: 0.0779
Epoch 48/100, Loss: 0.0674
Epoch 49/100, Loss: 0.0732
Epoch 50/100, Loss: 0.0725
Epoch 51/100, Loss: 0.0672
Epoch 52/100, Loss: 0.0639
Epoch 53/100, Loss: 0.0681
Epoch 54/100, Loss: 0.0636
Epoch 55/100, Loss: 0.0633
Epoch 56/100, Loss: 0.0652
Epoch 57/100, Loss: 0.0609
Epoch 58/100, Loss: 0.0577
Epoch 59/100, Loss: 0.0540
Epoch 60/100, Loss: 0.0579
Epoch 61/100, Loss: 0.0576
Epoch 62/100, Loss: 0.0688
Epoch 63/100, Loss: 0.0546
Epoch 64/100, Loss: 0.0509
Epoch 65/100, Loss: 0.0495
Epoch 66/100, Loss: 0.0507
Epoch 67/100, Loss: 0.0465
Epoch 68/100, Loss: 0.0462
Epoch 69/100, Loss: 0.0480
Epoch 70/100, Loss: 0.0405
Epoch 71/100, Loss: 0.0389
Epoch 72/100, Loss: 0.0389
Epoch 73/100, Loss: 0.0369
Epoch 74/100, Loss: 0.0380
Epoch 75/100, Loss: 0.0365
Epoch 76/100, Loss: 0.0345
Epoch 77/100, Loss: 0.0339
Epoch 78/100, Loss: 0.0355
Epoch 79/100, Loss: 0.0320
Epoch 80/100, Loss: 0.0307
Epoch 81/100, Loss: 0.0327
Epoch 82/100, Loss: 0.0300
Epoch 83/100, Loss: 0.0308
Epoch 84/100, Loss: 0.0305
Epoch 85/100, Loss: 0.0266
Epoch 86/100, Loss: 0.0249
Epoch 87/100, Loss: 0.0251
Epoch 88/100, Loss: 0.0242
Epoch 89/100, Loss: 0.0245
Epoch 90/100, Loss: 0.0254
Epoch 91/100, Loss: 0.0236
Epoch 92/100, Loss: 0.0239
Epoch 93/100, Loss: 0.0235
Epoch 94/100, Loss: 0.0214
Epoch 95/100, Loss: 0.0198
Epoch 96/100, Loss: 0.0211
Epoch 97/100, Loss: 0.0193
Epoch 98/100, Loss: 0.0188
Epoch 99/100, Loss: 0.0225
Epoch 100/100, Loss: 0.0203

In [31]:
# Evaluate the model
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb) #[0.2, 0.3, 0.5, -0.5, ..] - 7 vals
        max_val, max_idx = torch.max(outputs, 1) #returns max value and index of max value

        correct += (max_idx == yb).sum().item()
        total += yb.size(0) # Actual number of samples in the each batch

In [32]:
y_train.shape

(718,)

In [33]:
y_test.shape

(180,)

In [35]:
print("Total samples in test set:", total)
print("Correct predictions:", correct)
print("Accuracy:", correct / total * 100, "%")

Total samples in test set: 180
Correct predictions: 169
Accuracy: 93.88888888888889 %

In [36]:
import torch, joblib

torch.save(model.state_dict(), "pomology_model.pth")
joblib.dump(scaler, "scaler.pkl")
joblib.dump(le, "label_encoder.pkl")   # ← this one is critical
print("✅ All artifacts exported")

✅ All artifacts exported